name       : wxwidgets2.8
version    : 2.8.12
release    : 9
source     :
    - https://github.com/wxWidgets/wxWidgets/releases/download/v2.8.12/wxWidgets-2.8.12.tar.gz : 197c94f7d46269a7fc261a3c8c943f03a9807acf65381944489a538fd8b5dd21
license    : wxWindows # https://github.com/wxWidgets/wxWidgets/blob/master/docs/licence.txt
component  : desktop.library
summary    : GTK+ implementation of wxWidgets API for GUI
description: |
    GTK+ implementation of wxWidgets API for GUI
builddeps  :
    - pkgconfig(gconf-2.0)
    - pkgconfig(glu)
    - pkgconfig(gstreamer-0.10)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(sdl)
    - pkgconfig(libmspack)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(xt)
    - pkgconfig(xxf86vm)
    - pkgconfig(xpm)
setup      : |
    %patch -p1 < $pkgfiles/wxGTK-collision.patch
    %patch -Np1 < $pkgfiles/make-abicheck-non-fatal.patch
    %patch -p1 < $pkgfiles/wxGTK-2.8.12.1-fix-c++14.patch
    %configure --disable-static \
        --disable-precomp-headers \
        --enable-graphics_ctk \
        --enable-mediactrl \
        --enable-unicode \
        --with-gtk=2 \
        --with-libjpeg=sys \
        --with-opengl \
        --with-regex=builtin \
        --with-sdl \
        --with-tiff=sys
build      : |
    %make
    %make -C locale allmo
    %make -C contrib/src
install    : |
    %make_install
    %make_install -C contrib/src
